In [16]:
import numpy as np

In [17]:
scores = np.random.randint(0, 20, (20, 4))
scores

array([[ 5, 10,  7, 11],
       [ 3,  4,  1, 10],
       [13,  7,  9, 19],
       [ 3, 18, 18, 11],
       [ 9, 15,  3,  5],
       [12, 19,  3, 14],
       [10, 15,  0, 13],
       [ 8,  9, 10, 13],
       [ 4,  6,  8,  2],
       [ 8,  9,  0, 18],
       [ 6,  4, 13, 15],
       [ 4,  1,  1,  3],
       [ 5, 15,  7,  3],
       [ 5, 16,  3,  2],
       [ 0, 11, 16,  4],
       [ 9,  7, 11,  4],
       [15,  8,  0,  3],
       [18, 11,  7, 10],
       [10, 14,  0,  7],
       [15, 16, 17,  3]])

In [18]:
scores + 10

array([[15, 20, 17, 21],
       [13, 14, 11, 20],
       [23, 17, 19, 29],
       [13, 28, 28, 21],
       [19, 25, 13, 15],
       [22, 29, 13, 24],
       [20, 25, 10, 23],
       [18, 19, 20, 23],
       [14, 16, 18, 12],
       [18, 19, 10, 28],
       [16, 14, 23, 25],
       [14, 11, 11, 13],
       [15, 25, 17, 13],
       [15, 26, 13, 12],
       [10, 21, 26, 14],
       [19, 17, 21, 14],
       [25, 18, 10, 13],
       [28, 21, 17, 20],
       [20, 24, 10, 17],
       [25, 26, 27, 13]])

In [19]:
np.add(10, scores)

array([[15, 20, 17, 21],
       [13, 14, 11, 20],
       [23, 17, 19, 29],
       [13, 28, 28, 21],
       [19, 25, 13, 15],
       [22, 29, 13, 24],
       [20, 25, 10, 23],
       [18, 19, 20, 23],
       [14, 16, 18, 12],
       [18, 19, 10, 28],
       [16, 14, 23, 25],
       [14, 11, 11, 13],
       [15, 25, 17, 13],
       [15, 26, 13, 12],
       [10, 21, 26, 14],
       [19, 17, 21, 14],
       [25, 18, 10, 13],
       [28, 21, 17, 20],
       [20, 24, 10, 17],
       [25, 26, 27, 13]])

In [20]:
scores - 20

array([[-15, -10, -13,  -9],
       [-17, -16, -19, -10],
       [ -7, -13, -11,  -1],
       [-17,  -2,  -2,  -9],
       [-11,  -5, -17, -15],
       [ -8,  -1, -17,  -6],
       [-10,  -5, -20,  -7],
       [-12, -11, -10,  -7],
       [-16, -14, -12, -18],
       [-12, -11, -20,  -2],
       [-14, -16,  -7,  -5],
       [-16, -19, -19, -17],
       [-15,  -5, -13, -17],
       [-15,  -4, -17, -18],
       [-20,  -9,  -4, -16],
       [-11, -13,  -9, -16],
       [ -5, -12, -20, -17],
       [ -2,  -9, -13, -10],
       [-10,  -6, -20, -13],
       [ -5,  -4,  -3, -17]])

In [21]:
np.subtract(20, scores)

array([[15, 10, 13,  9],
       [17, 16, 19, 10],
       [ 7, 13, 11,  1],
       [17,  2,  2,  9],
       [11,  5, 17, 15],
       [ 8,  1, 17,  6],
       [10,  5, 20,  7],
       [12, 11, 10,  7],
       [16, 14, 12, 18],
       [12, 11, 20,  2],
       [14, 16,  7,  5],
       [16, 19, 19, 17],
       [15,  5, 13, 17],
       [15,  4, 17, 18],
       [20,  9,  4, 16],
       [11, 13,  9, 16],
       [ 5, 12, 20, 17],
       [ 2,  9, 13, 10],
       [10,  6, 20, 13],
       [ 5,  4,  3, 17]])

In [22]:
scores * 2

array([[10, 20, 14, 22],
       [ 6,  8,  2, 20],
       [26, 14, 18, 38],
       [ 6, 36, 36, 22],
       [18, 30,  6, 10],
       [24, 38,  6, 28],
       [20, 30,  0, 26],
       [16, 18, 20, 26],
       [ 8, 12, 16,  4],
       [16, 18,  0, 36],
       [12,  8, 26, 30],
       [ 8,  2,  2,  6],
       [10, 30, 14,  6],
       [10, 32,  6,  4],
       [ 0, 22, 32,  8],
       [18, 14, 22,  8],
       [30, 16,  0,  6],
       [36, 22, 14, 20],
       [20, 28,  0, 14],
       [30, 32, 34,  6]])

In [23]:
np.multiply(2, scores)

array([[10, 20, 14, 22],
       [ 6,  8,  2, 20],
       [26, 14, 18, 38],
       [ 6, 36, 36, 22],
       [18, 30,  6, 10],
       [24, 38,  6, 28],
       [20, 30,  0, 26],
       [16, 18, 20, 26],
       [ 8, 12, 16,  4],
       [16, 18,  0, 36],
       [12,  8, 26, 30],
       [ 8,  2,  2,  6],
       [10, 30, 14,  6],
       [10, 32,  6,  4],
       [ 0, 22, 32,  8],
       [18, 14, 22,  8],
       [30, 16,  0,  6],
       [36, 22, 14, 20],
       [20, 28,  0, 14],
       [30, 32, 34,  6]])

In [24]:
np.std(scores)

np.float64(5.431375861602657)

In [25]:
np.var(scores)

np.float64(29.499843750000004)

In [26]:
np.cos(scores)

array([[ 0.28366219, -0.83907153,  0.75390225,  0.0044257 ],
       [-0.9899925 , -0.65364362,  0.54030231, -0.83907153],
       [ 0.90744678,  0.75390225, -0.91113026,  0.98870462],
       [-0.9899925 ,  0.66031671,  0.66031671,  0.0044257 ],
       [-0.91113026, -0.75968791, -0.9899925 ,  0.28366219],
       [ 0.84385396,  0.98870462, -0.9899925 ,  0.13673722],
       [-0.83907153, -0.75968791,  1.        ,  0.90744678],
       [-0.14550003, -0.91113026, -0.83907153,  0.90744678],
       [-0.65364362,  0.96017029, -0.14550003, -0.41614684],
       [-0.14550003, -0.91113026,  1.        ,  0.66031671],
       [ 0.96017029, -0.65364362,  0.90744678, -0.75968791],
       [-0.65364362,  0.54030231,  0.54030231, -0.9899925 ],
       [ 0.28366219, -0.75968791,  0.75390225, -0.9899925 ],
       [ 0.28366219, -0.95765948, -0.9899925 , -0.41614684],
       [ 1.        ,  0.0044257 , -0.95765948, -0.65364362],
       [-0.91113026,  0.75390225,  0.0044257 , -0.65364362],
       [-0.75968791, -0.

In [27]:
np.percentile(scores, 75)

np.float64(13.0)

In [28]:
nums = [1, 2, 3, 4, 5, 6, 7]
nums

[1, 2, 3, 4, 5, 6, 7]

In [29]:
np.mean(nums)

np.float64(4.0)

In [30]:
np.median(nums)

np.float64(4.0)

In [31]:
np.quantile(nums, 0.25)

np.float64(2.5)

In [32]:
np.quantile(nums, 0.5)

np.float64(4.0)

In [33]:
np.quantile(nums, 0.75)

np.float64(5.5)

In [34]:
np.percentile(nums, 75)

np.float64(5.5)