In [1]:
import numpy as np

In [3]:
mtrx = np.array([[1, 2], [3, 4], [5, 6]])
mtrx

array([[1, 2],
       [3, 4],
       [5, 6]])

In [4]:
mtrx.shape

(3, 2)

# reshape

In [5]:
mtrx.reshape(2, 3)

array([[1, 2, 3],
       [4, 5, 6]])

In [9]:
mtrx.reshape(3, 3)

ValueError: cannot reshape array of size 6 into shape (3,3)

In [10]:
mtrx.reshape(3, -1)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [11]:
mtrx.reshape(1, -1)

array([[1, 2, 3, 4, 5, 6]])

In [12]:
mtrx.reshape(-1, 1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

# flatten

In [6]:
mtrx.flatten()

array([1, 2, 3, 4, 5, 6])

# ravel

In [7]:
mtrx.ravel()

array([1, 2, 3, 4, 5, 6])

In [8]:
np.ravel(mtrx)

array([1, 2, 3, 4, 5, 6])