In [2]:
import numpy as np

# Row Matrix

In [2]:
row = np.array([[1, 2, 3, 4, 5]])
row

array([[1, 2, 3, 4, 5]])

# Column Matrix

In [3]:
col = row.reshape(-1, 1)
col

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [4]:
col.shape

(5, 1)

# Squared Matrix

In [23]:
sq = np.array([[1, 2, 5], [3, 4, 6], [7, 8, 9]])
sq

array([[1, 2, 5],
       [3, 4, 6],
       [7, 8, 9]])

# Diagonal Matrix

In [7]:
diag = np.diag([1, 2, 3, 4])
diag

array([[1, 0, 0, 0],
       [0, 2, 0, 0],
       [0, 0, 3, 0],
       [0, 0, 0, 4]])

In [5]:
np.diag(sq)

array([1, 4])

In [6]:
np.diag(np.fliplr(sq))

array([2, 3])

# Ones

In [13]:
ones = np.ones((3, 3), dtype=np.int16)
ones

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]], dtype=int16)

## Ones-like

In [14]:
np.ones_like(sq)

array([[1, 1],
       [1, 1]])

# Zeros

In [16]:
zeros = np.zeros((4, 4))
zeros

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

## Zeros-like

In [17]:
np.zeros_like(sq)

array([[0, 0],
       [0, 0]])

# Full Matrix

In [20]:
full = np.full((4, 5), "Honey")
full

array([['Honey', 'Honey', 'Honey', 'Honey', 'Honey'],
       ['Honey', 'Honey', 'Honey', 'Honey', 'Honey'],
       ['Honey', 'Honey', 'Honey', 'Honey', 'Honey'],
       ['Honey', 'Honey', 'Honey', 'Honey', 'Honey']], dtype='<U5')

## Full-like

In [21]:
np.full_like(sq, 12)

array([[12, 12],
       [12, 12]])

# Upper Triangular

In [27]:
np.triu(sq)

array([[1, 2, 5],
       [0, 4, 6],
       [0, 0, 9]])

In [29]:
np.triu(sq, k=1)

array([[0, 2, 5],
       [0, 0, 6],
       [0, 0, 0]])

In [30]:
np.triu(sq, k=-1)

array([[1, 2, 5],
       [3, 4, 6],
       [0, 8, 9]])

# Lower Triangular

In [31]:
np.tril(sq)

array([[1, 0, 0],
       [3, 4, 0],
       [7, 8, 9]])

# Identity

In [32]:
np.eye(6)

array([[1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 1.]])